### ISSUE TITLE
Starke Artefaktbildung bei H.264 TS Streams mit ungültiger PES Längenangabe

### ISSUE THREAD

**Issue by Wanninger** [flensrocker/vdr-plugin-xineliboutput#1]
Seit einigen Wochen tritt auf einigen Astra Transpondern bei H.264 TS Streams, die ungültige PES Längenangaben enthalten, extrem starke Artefaktbildung auf.
Dieser Effekt ist sowohl bei Live-TV als auch bei Aufnahmen zu beobachten.
Wenn man die Aufnahme z.B. mit dem TS-Doctor bearbeitet, und die PES Längenangabe auf "0"
ändert, dann funktioniert die Wiedergabe dieser Aufnahme einwandfrei, ohne Artefakte.

Kann man den xineliboutput/vdr-sxfe sourcecode so verändern, dass er bei H.264 die PES Angabe einfach ignoriert?

Gruß Wanninger

**Comment by flensrocker** [comment]
Tut mir leid, dies ist nicht das offizielle Repository von xineliboutput. Du findest es hier:

https://projects.vdr-developer.org/git/xineliboutput.git/

Leider sehe ich da keinen Bugtracker, aber vielleicht kannst du die Autoren kontaktieren. All zu aktiv scheint das Plugin leider nicht mehr entwickelt zu werden.

**Comment by Wanninger** [comment]
Danke Dir!

Dann werde ich mal schauen ob Richtung Finnland noch was los ist...

Gruß

---

Am 28.12.2016 um 10:20 schrieb Lars Hanisch:
